name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install cmake cmake-curses-gui
          mkdir build && cd build
          cmake ..
          make
          ./test/test_random/test_random.out
