name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: see-loc-and-ver
        run: |
          pwd
          ls
          gfortran --version

      - name: update-ubuntu
        run: |
          sudo apt update
          sudo apt upgrade

      - name: install-env
        run: |
          sudo apt install cmake cmake-curses-gui

      - name: cmake-exec
        run: |
          cmake -B build
          cmake --build build
          cmake --build build --target test
